[package]
name = "network"
version = "0.1.0"
edition = "2021"


[dependencies]
io = "";
std::net::{TcpListener, TcpStream};
std::sync::{Arc, Mutex};
std::time::Duration;
crate::node::{Node, Transport};

